backend_application_port: 8000  # must be unique for each project on the same server
frontend_application_port: 3000  # must be unique for each project on the same server
environment_suffix: ""
project_slug: "{{ base_project_slug }}{{ environment_suffix }}"

public_hostname: telescoop.fr
redirect_hostname: www.telescoop.fr
url: "{{ public_hostname }}"
other_public_hostname: telescoop.fr
project_dir: "{{project_base_dir}}{{ environment_suffix }}"
backend_static_path: "{{ project_dir }}/backend_static"

frontend_branch: main

environment_name: production
